/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author jonathan
 */
public class CIConsultas extends javax.swing.JFrame {

    /**
     * Creates new form CIConsultas
     */
    public CIConsultas() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/bicycle_icon.jpg")).getIm­age());
          setTitle("CONSULTAS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConsutaPorKiosco = new javax.swing.JButton();
        btonRegresar = new javax.swing.JButton();
        btnConsutaMembresia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConsutaPorKiosco.setBackground(new java.awt.Color(0, 0, 0));
        btnConsutaPorKiosco.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        btnConsutaPorKiosco.setForeground(new java.awt.Color(255, 255, 255));
        btnConsutaPorKiosco.setText("Consulta de rentas por Kiosco");
        btnConsutaPorKiosco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsutaPorKioscoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsutaPorKiosco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 390, 60));

        btonRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btonRegresar.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        btonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btonRegresar.setText("Regresar");
        btonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 140, -1));

        btnConsutaMembresia.setBackground(new java.awt.Color(0, 0, 0));
        btnConsutaMembresia.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        btnConsutaMembresia.setForeground(new java.awt.Color(255, 255, 255));
        btnConsutaMembresia.setText("Consulta de uso de membresia");
        btnConsutaMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsutaMembresiaActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsutaMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 390, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menua.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsutaPorKioscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsutaPorKioscoActionPerformed
        try {
            new CIConsultasPorKiosco().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(CIConsultas.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        
    }//GEN-LAST:event_btnConsutaPorKioscoActionPerformed

    private void btonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonRegresarActionPerformed
        new CIMenuP().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btonRegresarActionPerformed

    private void btnConsutaMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsutaMembresiaActionPerformed
        new CIConsultaMembresia().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConsutaMembresiaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsutaMembresia;
    private javax.swing.JButton btnConsutaPorKiosco;
    private javax.swing.JButton btonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
